<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>12</LangVersion>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MahApps.Metro" Version="2.4.10" />
    <PackageReference Include="MahApps.Metro.IconPacks.Material" Version="5.0.0" />
    <PackageReference Include="Prism.DryIoc" Version="8.1.97" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TaskManager.Shared\TaskManager.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Lang\Strings.en.xaml" />
    <Resource Include="Resources\Lang\Strings.ru.xaml" />
  </ItemGroup>

</Project>
